-- MySQL Script generated by MySQL Workbench
-- Tue May  6 09:50:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipes` (
  `equipeID` INT NOT NULL AUTO_INCREMENT,
  `telefone` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `sexo` BINARY NOT NULL,
  PRIMARY KEY (`equipeID`),
  UNIQUE INDEX `equipeID_UNIQUE` (`equipeID` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `usuarioID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `sexo` BINARY NOT NULL,
  `telefone` INT(11) NOT NULL,
  `jornalista` TINYINT NOT NULL,
  PRIMARY KEY (`usuarioID`),
  UNIQUE INDEX `usuarioID_UNIQUE` (`usuarioID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jornalistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jornalistas` (
  `jornalistaID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` INT(11) NOT NULL,
  `Usuarios_usuarioID` INT NOT NULL,
  PRIMARY KEY (`jornalistaID`),
  UNIQUE INDEX `jornalistaID_UNIQUE` (`jornalistaID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_Jornalistas_Usuarios1_idx` (`Usuarios_usuarioID` ASC) VISIBLE,
  CONSTRAINT `fk_Jornalistas_Usuarios1`
    FOREIGN KEY (`Usuarios_usuarioID`)
    REFERENCES `mydb`.`Usuarios` (`usuarioID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias` (
  `noticiaID` INT NOT NULL,
  `texto` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `data_liberacao` DATETIME NOT NULL,
  `liberacao` TINYINT(4) NOT NULL,
  `data_revisao` DATETIME NOT NULL,
  `revisao` TINYINT(4) NOT NULL,
  `Equipes_equipeID` INT NOT NULL,
  `Jornalistas_jornalistaID` INT NOT NULL,
  PRIMARY KEY (`noticiaID`, `Equipes_equipeID`, `Jornalistas_jornalistaID`),
  UNIQUE INDEX `noticiaID_UNIQUE` (`noticiaID` ASC) VISIBLE,
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC) VISIBLE,
  UNIQUE INDEX `foto_UNIQUE` (`foto` ASC) VISIBLE,
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC) VISIBLE,
  INDEX `fk_Noticias_Equipes_idx` (`Equipes_equipeID` ASC) VISIBLE,
  INDEX `fk_Noticias_Jornalistas1_idx` (`Jornalistas_jornalistaID` ASC) VISIBLE,
  CONSTRAINT `fk_Noticias_Equipes`
    FOREIGN KEY (`Equipes_equipeID`)
    REFERENCES `mydb`.`Equipes` (`equipeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_Jornalistas1`
    FOREIGN KEY (`Jornalistas_jornalistaID`)
    REFERENCES `mydb`.`Jornalistas` (`jornalistaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Noticias_has_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Noticias_has_Usuarios` (
  `Usuarios_usuarioID` INT NOT NULL,
  `Noticias_noticiaID` INT NOT NULL,
  `Noticias_Equipes_equipeID` INT NOT NULL,
  `Noticias_Jornalistas_jornalistaID` INT NOT NULL,
  PRIMARY KEY (`Usuarios_usuarioID`, `Noticias_noticiaID`, `Noticias_Equipes_equipeID`, `Noticias_Jornalistas_jornalistaID`),
  INDEX `fk_Noticias_has_Usuarios_Noticias1_idx` (`Noticias_noticiaID` ASC, `Noticias_Equipes_equipeID` ASC, `Noticias_Jornalistas_jornalistaID` ASC) VISIBLE,
  CONSTRAINT `fk_Noticias_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_usuarioID`)
    REFERENCES `mydb`.`Usuarios` (`usuarioID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noticias_has_Usuarios_Noticias1`
    FOREIGN KEY (`Noticias_noticiaID` , `Noticias_Equipes_equipeID` , `Noticias_Jornalistas_jornalistaID`)
    REFERENCES `mydb`.`Noticias` (`noticiaID` , `Equipes_equipeID` , `Jornalistas_jornalistaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
